# Generated by pip2nix 0.8.0.dev1
# See https://github.com/nix-community/pip2nix

{ pkgs, fetchurl, fetchgit, fetchhg }:

self: super: {
  "attrs" = super.buildPythonPackage rec {
    pname = "attrs";
    version = "25.3.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/77/06/bb80f5f86020c4551da315d78b3ab75e8228f89f0162f2c3a819e407941a/attrs-25.3.0-py3-none-any.whl";
      sha256 = "1hrv1vjc46jqmnb1bxn6zybrm283dw910d3q82jzw08p0g71hws2";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "cattrs" = super.buildPythonPackage rec {
    pname = "cattrs";
    version = "25.1.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/18/b0/215274ef0d835bbc1056392a367646648b6084e39d489099959aefcca2af/cattrs-25.1.1-py3-none-any.whl";
      sha256 = "0r603hx0csmjn126clkddv0d85ndnjlrgq77lxwvxxra839v4h0v";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."attrs"
      self."exceptiongroup"
      self."typing-extensions"
    ];
  };
  "django-template-lsp" = super.buildPythonPackage rec {
    pname = "django-template-lsp";
    version = "1.2.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/86/19/518cb0d5133a2b22d32ee94b324e46409da69076f412b1f83448ceb7db14/django_template_lsp-1.2.0-py3-none-any.whl";
      sha256 = "0zndkrbafff6a7lfx391p2v6wklxdqk468yqk1ixs24r1zic33m2";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."jedi"
      self."pygls"
    ];
  };
  "exceptiongroup" = super.buildPythonPackage rec {
    pname = "exceptiongroup";
    version = "1.3.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/36/f4/c6e662dade71f56cd2f3735141b265c3c79293c109549c1e6933b0651ffc/exceptiongroup-1.3.0-py3-none-any.whl";
      sha256 = "044alxyhkfdlr5z3xlpnf5lv78310bnsgnkdmm669l0k1ip1w4ad";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."typing-extensions"
    ];
  };
  "jedi" = super.buildPythonPackage rec {
    pname = "jedi";
    version = "0.19.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/c0/5a/9cac0c82afec3d09ccd97c8b6502d48f165f9124db81b4bcb90b4af974ee/jedi-0.19.2-py2.py3-none-any.whl";
      sha256 = "1fdmxpv6wnyf7kg88irbyzd7925m7k4a70bnbkz5f3s9x2yj5vx8";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."parso"
    ];
  };
  "lsprotocol" = super.buildPythonPackage rec {
    pname = "lsprotocol";
    version = "2023.0.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/8d/37/2351e48cb3309673492d3a8c59d407b75fb6630e560eb27ecd4da03adc9a/lsprotocol-2023.0.1-py3-none-any.whl";
      sha256 = "1wk0582m2jbdb67mdk9nj8v7k0j3hxbkgihl5ckj8bxgwk4j6ln7";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."attrs"
      self."cattrs"
    ];
  };
  "parso" = super.buildPythonPackage rec {
    pname = "parso";
    version = "0.8.4";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/c6/ac/dac4a63f978e4dcb3c6d3a78c4d8e0192a113d288502a1216950c41b1027/parso-0.8.4-py2.py3-none-any.whl";
      sha256 = "061zsi1hchimzjzi538yxrw16yf3qmvw706wvp9aq7994056f654";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pygls" = super.buildPythonPackage rec {
    pname = "pygls";
    version = "1.3.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/11/19/b74a10dd24548e96e8c80226cbacb28b021bc3a168a7d2709fb0d0185348/pygls-1.3.1-py3-none-any.whl";
      sha256 = "07nr7pd6ifgbm52464j9gm66a7qkhrnlzh7anvg1ncjnzhgg203f";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."cattrs"
      self."lsprotocol"
    ];
  };
  "typing-extensions" = super.buildPythonPackage rec {
    pname = "typing-extensions";
    version = "4.14.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/b5/00/d631e67a838026495268c2f6884f3711a15a9a2a96cd244fdaea53b823fb/typing_extensions-4.14.1-py3-none-any.whl";
      sha256 = "0xhxfdahfwdkvr7nlxmlq8v4m94flhh29nkf3l1r7p3lhfsy7qfi";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
}
